# Generated by Django 4.1.4 on 2023-01-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagname',
        ),
        migrations.AddField(
            model_name='post',
            name='tagname',
            field=models.ManyToManyField(null=True, to='appMy.tagname', verbose_name='Tag name'),
        ),
    ]
