# Generated by Django 4.1.4 on 2023-01-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_remove_post_tagname_post_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tagname',
            field=models.ManyToManyField(to='appMy.tagname', verbose_name='Tag name'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Yorum Yapan')),
                ('title', models.CharField(max_length=50, verbose_name='Yorum Başlığı')),
                ('text', models.TextField(max_length=200, verbose_name='Yorum')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Zamanı')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.post', verbose_name='Yorum Yapılan Post')),
            ],
        ),
    ]
